version: '3'
services: 
  nodejs: 
    image: node_desafio_04
    restart: always
    build: .
    ports: 
      - 5678
    depends_on: 
      - db
  db: 
    image: postgres
    restart: always
    volumes: 
        - ./db_desafio04:/var/lib/postgresql/data
    ports: 
        - 5432
    environment:
        - POSTGRES_PASSWORD=mysecretpassword